### ISSUE TITLE
0.3.0 End Game

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode-java-test#119]
# Build
- [x] 2/11 - bump version to 0.3.0(pr #121) - @ansyral
- [x] 2/12 - Update change log for 0.3.0 - @ansyral
- [x] 2/12 - Signed RC Bits - @ansyral

# Test
- [x] 2/12 - Run test plan #49, verify bug #114 #83 - @bsaby @sallyur
- [x] 2/12 - Test basic feature on VSCode insider - @ansyral 
- [x] 2/12 - Verify bug #83 -@ansyral

# Release
- [x] 2/12 - Add 0.3.0 tag for vscode-java-test - @ansyral
- [x] 2/12 - Release to marketplace - @ansyral 

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by ansyral** [comment]
## simple maven project with tests whose package is default package
VSCode version:  1.20.0, 1.20.0-insider
OS version: window10
find an issue #123

**Comment by ansyral** [comment]
## maven project with multiple tests

VSCode version: 1.20.0-insider
OS version: windows10

- trigger tests from test explorer, all tests/project level/package level/class level/method level
- check status bar item color is correct
- check report. when opening the report, test explorer wouldn't disappear
- trigger test from codelens.

find **one issue**:  
1. trigger tests from class level, it would run all tests in the class, class codelens status is 'check mark'
2. run one method in the class, class's status would be updated from 'check mark' to 'question mark'

**Comment by bsaby** [comment]
# Run test plan
1. Configurations

Win10 x64 | Mac Sierra   10.12.4
-- | --
VSCode   1.20.0   JDK1.8.0_161 | VSCode   1.20.0   JDK1.8.0_144
2. Test result

Find known bugs: #65, #73, #74, #112, #123, #127 

Test case | Win10 x64 | Mac
-- | -- | --
Clean   install | Pass | Pass
Uninstall | Pass | Pass
Update | Pass | Pass
Test   explorer | #112 | #112
Test   explorer of Multi-root | Pass | Pass
Test   report | #74   #73 | #73  
Multi   module project | #65 | #65 
Test   status bar | Pass | Pass
Trigger   tests from test explorer | Pass | Pass
Open   test log command | Pass | Pass
Configure   test report position | Pass | Pass


# Verify bugs

Bugs | Windows | Mac
-- | -- | --
#114 |Pass | Pass
#83 | Pass | Pass
