### ISSUE TITLE
0.10.0 iteration plan

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-test#320]
Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

- [x] Sort packages alphabetically in Test Explorer #310 
- [x] Get java home location by calling the API exposed by LS #319
- [x] Code Lenses are not in the correct place #36 
- [x] BI improvement
