### ISSUE TITLE
0.2.0 Plan

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-test#43]
- [x] Test Explorer #45 
- [x] Show test statistics in status bar #46 
- [x] Should not prompt save when closing test log #23 
- [ ] Clear test result when test code changes #42 
- [x] Provide switch to optionally show output window #41 
- [ ] Use the right color scheme to show test case status vividly #47 
- [x] Fix #34 
- [x] Make test report more user friendly

Test Plan - #49

**Comment by ansyral** [comment]
#35 would be postponed as we need to redesign how to support a compound test(with parameter), etc.
