### ISSUE TITLE
0.12.0 Iteration Plan

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-test#451]
Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

- [x] Add `@DisplayName` support for JUnit 5 #446 
- [x] Support for JUnit 5 `@ParameterizedTests` #107
- [x] Upgrade to VS Code's webview API #397 
- [x] Add a way to persist logs into log file #452
