### ISSUE TITLE
0.14.0 Iteration Plan

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-test#562]
Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

## Add
- [X] Add the log level setting. #555
- [x] 💪 Support navigates to the source from the test report. #558

## Chang
- [x] Redesign the user experience about running/debugging with configuration. #524

## Fix
- [X] Fix the bug that test scope is wrong when triggering tests from inner class level. #411
- [X] Fix the bug that tests which contain inner class will be skipped if triggered from the test explorer. #460
- [X] Improve the test output format. #505
- [X] Pack the test report resources into the extension vsix. #550
