### ISSUE TITLE
0.2.0 Endgame

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode-java-test#60]
# Build
- [x] 12/21 - Bump version to 0.2.0 (PR #61 #63) - @ansyral 
- [x] 12/21 - Add change log for 0.2.0 - @ansyral
- [x] 12/21 - Signed RC Bits - @ansyral

# Test
- [x] 12/21 - Run test plan #49 - @bsaby @sallyur (found new bug #65 #66)
- [ ] 12/21 - Test multi-module project - @ansyral
- [x] 12/21 - Test report on Mac - @akaroml 
- [ ] 12/21 - Test test explorer for multiroot - @yaohaizh
- [ ] 12/21 - Test basic feature on Linux - @yaohaizh

# Release
- [ ] 12/22 - Add 0.2.0 tag for vscode-java-test - @ansyral
- [ ] 12/22 - Release to marketplace - @ansyral 

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by bsaby** [comment]
# Run test plan #49
1. Configuration

- Windows10: Vscode 1.19.1; jdk 1.8.0_152
- Mac: Vscode 1.19.1; jdk 1.8.0_144

2. Open Bugs:
#65 #66
3. Test result

Test case | Win10 x64 | Mac Sierra   10.12.4
-- | -- | --
Configurations | VSCode   1.19.1 x64   JDK1.8.0_151 x64 | VSCode   1.19.1   JDK1.8.0_144
Owner | Mona | Sally
Clean   install | Pass | Pass
Uninstall | Pass | Pass
Update | Pass | Pass
Test   explorer | Pass | Pass
Test   explorer of Multi-root | Pass | Pass
Test   report | Pass | Pass
Multi   module project | #65 [New] | #65 [New]
Test   status bar | #41 #46 | #41 #46

4. Bugs verification

bugs | Details | Expect | Windows | Mac
-- | -- | -- | -- | --
#1 | Can't save test   result file in vscode | Test   report readonly | Pass | Pass
#2 | The method test result content should be displayed wrapped | wrapped | Pass | Pass
#7 | Should always save   class test result file in multiple files with the same name? | Test   report readonly | Pass | Pass
#23 | Should not prompt   save when closing test log | Test   report readonly | Pass | Pass
#25 | Testcase summary   show duration "NaN" when disable one testcase in the test class | New   design | Pass | Pass

**Comment by ansyral** [comment]
# Build
- [ ] 1/5 - Update change log for 0.2.0 - @ansyral
- [ ] 1/5 - Signed RC Bits - @ansyral

# Test
- [ ] 1/5 - Run test plan #49 - @bsaby @sallyur
- [ ] 1/5 - Test multi-module project - @ansyral
- [ ] 1/5 - Test report on Mac - @akaroml 
- [ ] 1/5 - Test test explorer for multiroot - @akaroml 
- [ ] 1/5 - Test basic feature on Linux - @ansyral
- [ ] 1/5 - Test basic feature on VSCode insider - @ansyral

# Release
- [ ] 1/5 - Add 0.2.0 tag for vscode-java-test - @ansyral
- [ ] 1/5 - Release to marketplace - @ansyral 

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by ansyral** [comment]
# VSCode 1.20.0-insider

## test spring-petclinic

1.  open spring-petclinic project folder, verify that status bar has `Loading test` info
2.  [has bug!]run tests, after test finishes, status bar shows that "Failed to run tests", however the test succeeded with warning output.
3.  open test report,  also repro #74 
4.  open command panel to use 'java: show test output' command, it works. and vscode insider made some change to colorize output already

**Comment by bsaby** [comment]
#  Run test plan #49 

1. Configuration

- Windows10: Vscode 1.19.1;   jdk 1.8.0_152
- Mac: Vscode 1.19.1;    jdk 1.8.0_144

2. Open Bugs:
#81 
3. Test result:

Test case | Win10 x64 | Mac Sierra   10.12.4
-- | -- | --
Configurations | VSCode   1.19.1 x64   JDK1.8.0_151 x64 | VSCode   1.19.1   JDK1.8.0_144
Clean   install | Pass | Pass
Uninstall | Pass | Pass
Update | Pass | Pass
Test   explorer | Pass | Pass
Test   explorer of Multi-root | Pass | Pass
Test   report | #73  #81 | #73 #74 #81
Multi   module project | #65 | #65
Test   status bar | Pass | Pass

**Comment by akaroml** [comment]
Tested on Mac with spring-petclinic project.

1. Test cases were executed at both class level and member level
2. Test report was correctly generated from class, member and status bar
3. Status bar showed the correct state (running, test statistics)
4. Test output was shown when clicking the `Running tests...` on status bar
5. Test explorer showed test cases correctly
6. Jumped to test cases correctly by clicking tree nodes in test explorer
